version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: orders_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: orders_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - "5672:5672"   # porta para apps se conectarem
      - "15672:15672" # porta da UI de administração

  smtp:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: orders_smtp
    restart: always
    environment:
      - Urls=http://0.0.0.0:80
      - SmtpServer__IP=0.0.0.0
      - SmtpServer__Port=2525
    ports:
      - "2525:2525"
      - "8888:80"  # Interface web acessível em http://localhost:8888


volumes:
  postgres_data:
